[tool.poetry]
name = "iflyface"
version = "0.1.0"
description = ""
authors = ["p0ise <changelf@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
